version: '2'
services:
  microproject-postgresql:
    image: postgres:12.3
    volumes:
       - ~/volumes/jhipster/microproject/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
